### ISSUE TITLE
Creation of commodity tags

### ISSUE THREAD

**Issue by mrpozzi** [EST-Team-Adam/TheReadingMachine#1]
Tag the article with the commodity they are mostly related to. 
Maybe multiple commodities?

**Comment by albertomun** [comment]
Hi Luca!
I've a question: is it possible that many scraped articles are not strictly related to our commodities?
I've refined the classifier and, while testing it on sample of 1000 randomly selected articles, I noticed that 1/3 of them actually talk about agricolture.
... However should be still enough information!

**Comment by mrpozzi** [comment]
@albertomun what did you train the your classification model on?
remember that even if an article is not related to commodities (or to agriculture at all) may still be extremely predictive of the prices. Here we are trying to build features and, in this perspective, commodity tags are only one dimension.

**Comment by albertomun** [comment]
At the moment I'm applying on a sample a simple term frequency approach in order to identify new features while giving a first more robust classification to the articles. 
However I've just uploaded the results on my TheReadingMachine folder.
