### ISSUE TITLE
Identification of Labeled Data Sources

### ISSUE THREAD

**Issue by mrpozzi** [EST-Team-Adam/TheReadingMachine#10]
This entails both a literature review to understand how they have been labeled and some data mining to find already labeled text basis to build sentiment index

**Comment by mkao006** [comment]
There are some [Reuters Corpus](http://trec.nist.gov/data/reuters/reuters.html) that has been labelled already. Maybe we can build a model based on these data.

**Comment by mkao006** [comment]
Here is a list of dataset for me to investigate.

- [ ] [Wordnet](https://wordnet.princeton.edu/wordnet/related-projects/) and related projects
- [ ] [eXtended Wordnet](https://datahub.io/dataset/extended-wordnet)
- [ ] [WordNet 2.0](https://datahub.io/dataset/w3c-wordnet)
- [ ] [Movie review data](http://www.cs.cornell.edu/people/pabo/movie-review-data/)
- [ ] [NLP related dataset on data hub](https://datahub.io/dataset?tags=nlp)
- [ ] [The Ontologies of Linguistic Annotations](https://datahub.io/dataset/olia)

Also conduct literature review on these datasets to see how they are labelled.
