### ISSUE TITLE
Check what we can do with the Google NLP API

### ISSUE THREAD

**Issue by mkao006** [EST-Team-Adam/TheReadingMachine#12]
[Google NLP API](https://cloud.google.com/natural-language/)

**Comment by marcogarieri** [comment]
In particular [https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/language](python api for google nlp)

**Comment by albertomun** [comment]
I've Google NLP API up and running. 
It delivers Sentiment Analysis, Entity Analysis (which can be useful for articles classification) and Syntactic analysis.
Text to be analyzed is passed by a 'content' field. I tried to pass a few .txt files, I should check if our data format will create any problem.

**Comment by mkao006** [comment]
The [Microsoft concept graph](https://concept.research.microsoft.com/Home/API) might be useful as well

**Comment by mkao006** [comment]
Implemented by @albertomun .
