### ISSUE TITLE
Investigate the hour of 'dates' in the data

### ISSUE THREAD

**Issue by mkao006** [EST-Team-Adam/TheReadingMachine#16]
There seems to be some error in the hour/minutes of the data. It seems that the all the data are published within a 12 minute period after midnight. Although this is not first priority and has almost no impact to anything we are currently trying to achieve, but it would be something we need to bear in mind.

Below is the `set` of HH:MM:SS returned:

```
{u' 00:00:00',
 u' 00:01:00',
 u' 00:02:00',
 u' 00:03:00',
 u' 00:04:00',
 u' 00:05:00',
 u' 00:06:00',
 u' 00:07:00',
 u' 00:08:00',
 u' 00:09:00',
 u' 00:10:00',
 u' 00:11:00',
 u' 00:12:00'}
```

However, it should be important to obtain the timezone, as it can actually affect the date.

**Comment by mrpozzi** [comment]
@mkao006 take a look into how it is extracted in the scraper. I don't remember but it may be that there is only one blog that posts the hour (or it may be an automated job...) 

I would expect an histogram to show that the majority of the dates have ' 00:00:00' and that the majority of blogs have ' 00:00:00' only.

**Comment by mkao006** [comment]
Closing this issue as it is no longer relevant
