### ISSUE TITLE
Creation of Location tags

### ISSUE THREAD

**Issue by mrpozzi** [EST-Team-Adam/TheReadingMachine#2]
Tag the relevant location the article is referred to

**Comment by marcogarieri** [comment]
Database of cities and countries provided by [maxmind](https://www.maxmind.com/en/free-world-cities-database)

**Comment by marcogarieri** [comment]
As a first way to assign the location tags I used the following link as a [table](https://en.wikipedia.org/wiki/List_of_alternative_country_names) where the list of countries with alternatives names is provided. I then created a dictionary and assigned to the articles.
