### ISSUE TITLE
Dedupe Agrimoney links

### ISSUE THREAD

**Issue by mrpozzi** [EST-Team-Adam/TheReadingMachine#35]
clean up
http://www.agrimoney.com/news/farm-commodities-better-bet-than-gold-for-2010--1055.html
http://www.agrimoney.com/news/un-extends-round-of-cuts-to-world-wheat-forecasts--2174.html

**Comment by mrpozzi** [comment]
Addressed by PR #36

**Comment by marcogarieri** [comment]
Is this issue still open?

**Comment by mrpozzi** [comment]
Yes! I haven't fixed the issues with:

* Same article different sections
* Same article, slightly different links (as in the example above)

I think they are low priority, but we should keep track of them.

**Comment by marcosmilzo** [comment]
Agrimoney is now under subscription.
