### ISSUE TITLE
Bloomberg ToS Violation

### ISSUE THREAD

**Issue by marcogarieri** [EST-Team-Adam/TheReadingMachine#37]
Bloomberg cuts IPs off, when trying to run the scraper.
Action to be taken:
- [ ] check with Adam if we can get a Bloomberg API available

- [ ] try to test [update-ip](https://pypi.python.org/pypi/update-ip/0.2.1) to check if we can find a partial solution

**Comment by mrpozzi** [comment]
One comment is that option 1 might require a larger change in our pipeline (and it pisses me off to give up...)

**Comment by mkao006** [comment]
Can you guys submit a quick patch to the `dev` branch to remove `Bloomberg` for now, just remove `bloomberg` from the following line, there is no need to remove it completely. Then create a new patch branch for the new implementation.

```{python}
spiders = ['bloomberg', 'noggers', 'worldgrain', 'euractiv', 'agrimoney']
```

In addition, I think it is not a great idea for us to violate the ToS.

**Comment by marcogarieri** [comment]
At the moment we drop Bloomberg. 
If later on Adam Will give us access to FAO credentials we will include this back.

**Comment by mrpozzi** [comment]
I agree. that will require a whole new step in the pipeline.
