### ISSUE TITLE
Review of existing dictionaries

### ISSUE THREAD

**Issue by mrpozzi** [EST-Team-Adam/TheReadingMachine#6]
What's the state of the art in terms of sentiment dictionaries

**Comment by albertomun** [comment]
Existing dictionaries are

Subjectivity lexicon MPQA
http://mpqa.cs.pitt.edu/lexicons/subj_lexicon/

SentiWordNet
http://sentiwordnet.isti.cnr.it/

Harvard General Inquirer
http://www.wjh.harvard.edu/~inquirer/

A lexicon by Bing Liu
https://www.cs.uic.edu/~liub/
http://www.cs.uic.edu/~liub/FBS/opinion-lexicon-English.rar

Linguistic Inquiry and Word Counts (Proprietary)
http://liwc.wpengine.com/

**Comment by albertomun** [comment]
Dictionaries reviewis ready, it can be found with a few lexicons at the following URL

https://github.com/EST-Team-Adam/TheReadingMachine/tree/Alberto/Dictionaries_Review

**Comment by albertomun** [comment]
Lexicoder (available only for academic purposes)
http://www.lexicoder.com/index.html

Loughran and McDonald Financial Sentiment Dictionary
https://www3.nd.edu/~mcdonald/Word_Lists.html
